name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Unit test
      run: node index.js
